services:
  backend:
    build: ./back/
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"

  frontend:
    build: ./front/
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend