FROM python:3.10.17-alpine3.21

RUN apk update && apk add bash
RUN apk add --no-cache python3-dev gcc musl-dev libffi-dev linux-headers

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app

RUN python3 -m pip install --no-cache-dir -r requirements.txt
EXPOSE 8080
CMD ["python3", "app.py"]
