FROM python:3.10.17-alpine3.21

RUN apk update && apk add bash

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN python3 -m pip install --no-cache-dir -r requirements.txt
EXPOSE 8080
