# Dockerfile para desarrollo
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY tsconfig*.json ./
COPY src ./src

EXPOSE 5173

# Usa Vite para desarrollo
CMD ["npm", "run", "dev"]